[project]
name = "ice-cream-dataops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ho-jaein", email = "jaein.jang@hanwha.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cognite-sdk==7.89.0",
    "cognite-toolkit==0.6.53",
    "orjson>=3.12.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
ice-cream-dataops = "ice_cream_dataops:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
